import React, { useContext } from "react";
import { ApolloProvider } from "@apollo/client";
import { Inter } from "next/font/google";
import { ApolloClient, InMemoryCache } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  uri: "http://localhost:8080/api/graphql",
  cache: new InMemoryCache(),
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </>
  );
};

export default RootLayout;
